name = "tilts-api"
main = "src/worker.js"
compatibility_date = "2024-07-25"

[env.production]
name = "tilts-api-production"
route = "api.tilts.com/*"
kv_namespaces = [
  { binding = "SESSIONS", id = "your-kv-namespace-id" }
]

[env.production.vars]
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "your-anon-key"
PUSHER_APP_ID = "your-pusher-app-id"
PUSHER_KEY = "your-pusher-key"
PUSHER_SECRET = "your-pusher-secret"
PUSHER_CLUSTER = "us2"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "tilts-storage"

[[durable_objects.bindings]]
name = "GAME_SESSIONS"
class_name = "GameSession"